# 입양을 간 기록이 있지만 보호소에 들어온 기록이 없는 동물의 ID와 이름
# ID를 기준으로 오름차순 
SELECT O.ANIMAL_ID, O.NAME
FROM ANIMAL_INS I 
RIGHT OUTER JOIN ANIMAL_OUTS O
ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.DATETIME IS NULL
ORDER BY I.ANIMAL_ID