SELECT MONTH(A.START_DATE) AS MONTH, A.CAR_ID, COUNT(A.CAR_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
INNER JOIN (
SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE MONTH(START_DATE) IN (8, 9, 10) AND YEAR(START_DATE) = 2022
GROUP BY CAR_ID
HAVING COUNT(*) >= 5) B
ON A.CAR_ID = B.CAR_ID
WHERE MONTH(A.START_DATE) IN (8, 9, 10) AND YEAR(A.START_DATE) = 2022
GROUP BY MONTH, CAR_ID
ORDER BY MONTH, CAR_ID DESC