# 리뷰를 가장 많이 작성한 회원의 리뷰
# 회원 이름, 리뷰 텍스트, 리뷰 작성일
# 리뷰 작성일을 기준으로 오름차순, 같다면 리뷰 텍스트를 기준으로 오름차순
SELECT M.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE M JOIN REST_REVIEW R
ON M.MEMBER_ID = R.MEMBER_ID
JOIN (SELECT MEMBER_ID, COUNT(REVIEW_TEXT) AS COUNTS
      FROM REST_REVIEW
      GROUP BY MEMBER_ID
      ORDER BY COUNTS DESC
      LIMIT 1) C
ON M.MEMBER_ID = C.MEMBER_ID
ORDER BY R.REVIEW_DATE, R.REVIEW_TEXT