# 저자 ID 기준 오름차순, 카테고리 순으로 내림차순 정렬
# 2022년 1월의 도서 판매 데이터를 기준
SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(S.SALES * B.PRICE) AS TOTAL_SALES
FROM BOOK_SALES S LEFT OUTER JOIN BOOK B
ON S.BOOK_ID = B.BOOK_ID
LEFT OUTER JOIN AUTHOR A
ON A.AUTHOR_ID = B.AUTHOR_ID
WHERE YEAR(S.SALES_DATE) = 2022 AND MONTH(S.SALES_DATE) = 1
GROUP BY A.AUTHOR_ID, B.CATEGORY
ORDER BY A.AUTHOR_ID, B.CATEGORY DESC