# DEVELOPERS에서 FROMT END 스킬을 가진 개발자의 ID, 이메일, 이름, 성
# ID를 기준으로 오름차순 정렬
SELECT DISTINCT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS D
JOIN SKILLCODES C
ON D.SKILL_CODE & C.CODE = C.CODE
WHERE C.CATEGORY = 'FRONT END'
ORDER BY D.ID