# 물고기 종류별로 가장 큰 물고기의 ID, 이름, 길이
SELECT I.ID, N.FISH_NAME, I.LENGTH
FROM FISH_INFO I LEFT JOIN FISH_NAME_INFO N 
ON I.FISH_TYPE = N.FISH_TYPE
WHERE (N.FISH_TYPE, I.LENGTH) IN (
SELECT FISH_TYPE, MAX(LENGTH)
FROM FISH_INFO
GROUP BY FISH_TYPE)
ORDER BY I.ID