SELECT COUNT(*) AS FISH_COUNT, MAX(LENGTH) AS MAX_LENGTH, FISH_TYPE
FROM (SELECT FISH_TYPE, 
      CASE WHEN LENGTH IS NULL THEN 10 ELSE LENGTH END AS LENGTH
     FROM FISH_INFO) A
GROUP BY A.FISH_TYPE
HAVING AVG(A.LENGTH) >= 33
ORDER BY A.FISH_TYPE