# 상품코드 별 매출액(판매가 * 판매량) 합계
# 매출액 기준 내림차순, 매출액이 같다면 상품코드를 기준으로 오름차순
SELECT P.PRODUCT_CODE, SUM(P.PRICE * O.SALES_AMOUNT) AS SALES
FROM PRODUCT P JOIN OFFLINE_SALE O 
ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, P.PRODUCT_CODE